channels:
- conda-forge
dependencies:
# Jupyter
- jupyterlab=3.2
- jupyter-offlinenotebook=0.2
- nodejs=12
- nbconvert=6
- numpy=1.21.6
- matplotlib=3.2.2

# RTC
- jupyterlab-link-share=0.2
# Python Kernel
- ipykernel=5.1
#- matplotlib=3.1
- pandas=1
- python=3.7
- scikit-image=0.15
- scikit-learn=0.21
#- seaborn=0.11
- pip
- hmmlearn=0.2.7
- pip:
    - tensorflow-datasets==3.0.0 # datasets repository, ready to use
    - tensorflow-hub==0.9.0      # trained ML models repository, ready to use
    - tensorflow==2.8.2          # Deep Learning library
    - tf-keras-vis==0.8.1        # Saliency map and GradCam
    - Bio
   `
